baseurl = "https://faraimadzima.com/"
languageCode = "en-us"
publishdir = "public"
title = "Farai Madzima â€” Designer, Speaker & Conference Organiser"
theme = "F-2016"
[taxonomies]
  category = "categories"
  tag = "tags"
[Params]
  Author = "Farai Madzima"
  description = "ğŸ‘‹ğŸ¾ I'm Farai Madzima, a Zimbabwean interaction designer, conference organiser, and speaker living in Canada."
  avatarImg = "img/smiley-farai-madzima-3-4.jpg"